module.exports = [
    {
        name: "ONE MORE LIGHT LIVE",
        img: "data/discs/images/one_more_light_live.jpg",
        type: "ALBUM",
        url : "https://open.spotify.com/album/0zcNtUZ2oEpRmiDuWBFvcX?si=CJqc7CRASJKBoGq1ejmUGQ",
        price: 21.95,
    },
    {
        name: "CASTLE OF GLASS",
        img: "data/discs/images/castle_of_glass.jpg",
        type: "SINGLE",
        url : "https://open.spotify.com/track/1r1fPuhj9H4VdXr7OK6FL5?si=8ndbOaD_QgC8T9HnHtLAjg",
        price: 4.25,
    },
    {
        name: "IRIDESCENT",
        img: "data/discs/images/iridescent.jpg",
        type: "SINGLE",
        url: "https://open.spotify.com/track/69ZEgPX0hxWXJIqkTlYz41?si=wRb8o0CTThKpyvyKXTSo2A",
        price: 3.99,
    },
    {
        name: "LIVING THINGS",
        img: "data/discs/images/living_things.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/album/4XHIjbhjRmqWlosjj5rqSI?si=PU6pHYJYTwiLPqSqTH8w8Q",
        price: 15.50,
    },
    {
        name: "METEORA",
        img: "data/discs/images/meteora.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/album/4Gfnly5CzMJQqkUFfoHaP3?si=wDfcsfqjQOGORAp1NQfe0Q",
        price: 18.99,
    },
    {
        name: "FINAL MASQUERADE",
        img: "data/discs/images/final_masquerade.jpg",
        type: "SINGLE",
        url: "https://open.spotify.com/track/3aYBjxTMvrEOP0A0UXg9ER?si=LH5DpyWeQB2IRYgr1TBC2A",
        price: 5.50,
    },
    {
        name: "MINUTES TO MIDNIGHT",
        img: "data/discs/images/minutes_to_midnight.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/album/2tlTBLz2w52rpGCLBGyGw6?si=bfDxiqJ3R9OmcYA-fkZF7Q",
        price: 24.19,
    },
    {
        name: "NEW DIVIDE",
        img: "data/discs/images/new_divide.jpg",
        type: "SINGLE",
        url: "https://open.spotify.com/track/6Wx88Mv6b9ofjKMKkdwOJd?si=cvKgJgT5T9CBa8Caxb65SA",
        price: 6.25,
    },
    {
        name: "ONE MORE LIGHT",
        img: "data/discs/images/one_more_light.jpg",
        type: "SINGLE",
        url :"https://open.spotify.com/track/3xXBsjrbG1xQIm1xv1cKOt?si=cuPaOjjvT-uScyUqo77Qsg",
        price: 5.00,
    },
    {
        name: "REBELLION",
        img: "data/discs/images/rebellion.jpg",
        type: "SINGLE",
        url : "https://open.spotify.com/track/3zZ009FB8sc8JghwVrbLFq?si=JPeLMR_ISJazr3yEgqlAzg",
        price: 3.99,
    },
    {
        name: "RECHARGED",
        img: "data/discs/images/recharged.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/album/2FUsvD1bw53HGOjAg56vRD?si=DRSuq48tQ9mNuOSkG-3c4w",
        price: 23.99,
    },
    {
        name: "UNTIL IT´S GONE",
        img: "data/discs/images/until_its_gone.jpg",
        type: "SINGLE",
        url: "https://open.spotify.com/track/2n1jBz26dVBtSbMvJNjGsu?si=kGrcJEOtTUCZqo-dHp6R3g",
        price: 5.59,
    }
]