module.exports = [
    {
        name: "ONE MORE LIGHT LIVE",
        img: "data/discs/images/one_more_light_live.jpg",
        type: "ALBUM",
        url : "https://open.spotify.com/embed/album/0zcNtUZ2oEpRmiDuWBFvcX",
        price: 21.95,
        year: 2017,
    },
    {
        name: "CASTLE OF GLASS",
        img: "data/discs/images/castle_of_glass.jpg",
        type: "SONG",
        url : "https://open.spotify.com/embed/track/1r1fPuhj9H4VdXr7OK6FL5",
        price: 4.25,
        year: 2012,
    },
    {
        name: "IRIDESCENT",
        img: "data/discs/images/iridescent.jpg",
        type: "SONG",
        url: "https://open.spotify.com/embed/track/69ZEgPX0hxWXJIqkTlYz41",
        price: 3.99,
        year: 2010,
    },
    {
        name: "LIVING THINGS",
        img: "data/discs/images/living_things.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/embed/album/4XHIjbhjRmqWlosjj5rqSI",
        price: 15.50,
        year: 2012,
    },
    {
        name: "METEORA",
        img: "data/discs/images/meteora.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/embed/album/4Gfnly5CzMJQqkUFfoHaP3",
        price: 18.99,
        year: 2003,
    },
    {
        name: "FINAL MASQUERADE",
        img: "data/discs/images/final_masquerade.jpg",
        type: "SONG",
        url: "https://open.spotify.com/embed/track/3aYBjxTMvrEOP0A0UXg9ER",
        price: 5.50,
        year: 2014,
    },
    {
        name: "MINUTES TO MIDNIGHT",
        img: "data/discs/images/minutes_to_midnight.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/embed/album/2tlTBLz2w52rpGCLBGyGw6",
        price: 24.19,
        year: 2007,
    },
    {
        name: "NEW DIVIDE",
        img: "data/discs/images/new_divide.jpg",
        type: "SONG",
        url: "https://open.spotify.com/embed/track/6Wx88Mv6b9ofjKMKkdwOJd",
        price: 6.25,
        year: 2009,
    },
    {
        name: "ONE MORE LIGHT",
        img: "data/discs/images/one_more_light.jpg",
        type: "SONG",
        url :"https://open.spotify.com/embed/track/3xXBsjrbG1xQIm1xv1cKOt",
        price: 5.00,
        year: 2017,
    },
    {
        name: "REBELLION",
        img: "data/discs/images/rebellion.jpg",
        type: "SONG",
        url : "https://open.spotify.com/embed/track/3zZ009FB8sc8JghwVrbLFq",
        price: 3.99,
        year: 2014,
    },
    {
        name: "RECHARGED",
        img: "data/discs/images/recharged.jpg",
        type: "ALBUM",
        url: "https://open.spotify.com/embed/album/2FUsvD1bw53HGOjAg56vRD",
        price: 23.99,
        year: 2013,
    },
    {
        name: "UNTIL IT´S GONE",
        img: "data/discs/images/until_its_gone.jpg",
        type: "SONG",
        url: "https://open.spotify.com/embed/track/2n1jBz26dVBtSbMvJNjGsu",
        price: 5.59,
        year: 2014,
    }
]